parameters:
#    harvest_cloud_market_place_core.example.class: HarvestCloud\MarketPlace\CoreBundle\Example

services:
#    harvest_cloud_market_place_core.example:
#        class: %harvest_cloud_market_place_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
